const PRODUCT_ACTION_TYPES = {
  FETCH_PRODUCT_START: "productDetails/FETCH_PRODUCT_START",
  FETCH_PRODUCT_SUCCESS: "productDetails/FETCH_PRODUCT_SUCCESS",
  FETCH_PRODUCT_FAILED: "productDetails/FETCH_PRODUCT_FAILED",
};

export default PRODUCT_ACTION_TYPES;
